---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
  merge_group:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  ci:
    name: CI OTP-${{matrix.otp-version}}

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        otp-version: [24, 25, 26, 27]
        os: [ubuntu-24.04]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        id: setup-beam
        with:
          otp-version: ${{matrix.otp-version}}
          rebar3-version: 3.23.0

      - name: Restore _build
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: _build
          key: "_build-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}-${{hashFiles('rebar.config')}}"

      - name: Restore rebar3's cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.cache/rebar3
          key: "rebar3-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"

      - name: Continuous Integration (Polyfill)
        if: ${{fromJSON(matrix.otp-version) < 27}}
        run: |
          rebar3 as test polyfill_ci

      - name: Continuous Integration
        if: ${{fromJSON(matrix.otp-version) >= 27}}
        run: |
          rebar3 as test ci

      - name: Check if build left artifacts
        run: |
          rebar3 unlock --all
          rebar3 upgrade --all
          git diff --exit-code
