---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
  merge_group:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  ci:
    name: OTP-${{matrix.otp-version}}

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        otp-version: [25, 26, 27]
        os: [ubuntu-24.04]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        id: setup-beam
        with:
          otp-version: ${{matrix.otp-version}}
          rebar3-version: 3.23.0

      - name: Restore _build
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: _build
          key: "_build-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}-${{hashFiles('rebar.config')}}"

      - name: Restore rebar3's cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.cache/rebar3
          key: "rebar3-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"

      - name: Continuous Integration (Polyfill)
        if: ${{matrix.otp-version != '27'}}
        run: |
          rebar3 as test polyfill_ci

      - name: Continuous Integration
        if: ${{matrix.otp-version == '27'}}
        run: |
          rebar3 as test ci

      - name: Check if build left artifacts
        run: |
          rebar3 unlock --all
          rebar3 upgrade --all
          git diff --exit-code
