---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
  merge_group:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  ci:
    name: CI OTP-${{matrix.otp-version}}

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        otp-version: [24, 25, 26, 27]
        os: [ubuntu-24.04]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        id: setup-beam
        with:
          otp-version: ${{matrix.otp-version}}
          rebar3-version: 3.23.0

      - name: Restore _build
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: _build
          key: "_build-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}-${{hashFiles('rebar.config')}}"

      - name: Restore rebar3's cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ~/.cache/rebar3
          key: "rebar3-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"

      - name: Continuous Integration (Polyfill)
        if: ${{fromJSON(matrix.otp-version) < 27}}
        run: |
          rebar3 as test polyfill_ci

      - name: Continuous Integration
        if: ${{fromJSON(matrix.otp-version) >= 27}}
        run: |
          rebar3 as test ci

      - name: Check if build left artifacts
        run: |
          rebar3 unlock --all
          rebar3 upgrade --all
          git diff --exit-code
