---
name: Lint

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
  merge_group:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      # uses .markdownlint.yml for configuration
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v20.0.0
        with:
          globs: |
            .github/**/*.md
            *.md

      - name: yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          file_or_dir: |
            .github/**/*.yml
            .*.yml
          strict: true
          config_file: .yamllint.yml

      - name: actionlint
        uses: reviewdog/action-actionlint@2085657ab2c7f48c58edcc767fba576f63bea76b # v1.77.0
        env:
          SHELLCHECK_OPTS: -o all
